# Name(s)
# Gabriel Barney

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

- Honestly, the Jupyter Notebook is pretty clear. Rather than having questions on this, I am moreso confused on Pandas. I am going to do more research on it as time goes on to 

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [4]:
# YOUR SOLUTION HERE
import numpy as n
a = n.ones((6,4))*2
a

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

## Exercise 2

In [5]:
# YOUR SOLUTION HERE
b = n.ones((6,4))
b[range(4),range(4)] = 3
b

array([[3., 1., 1., 1.],
       [1., 3., 1., 1.],
       [1., 1., 3., 1.],
       [1., 1., 1., 3.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Exercise 3

In [6]:
# YOUR SOLUTION HERE
a*b
#n.dot(a,b)
"""We can multiply each value of matrix a to the value in the
corresponding coordinate of matrix b, but we cannot take the dot
product because the second dimension of matrix a does not match
the first dimension of matrix b."""

'We can multiply each value of matrix a to the value in the\ncorresponding coordinate of matrix b, but we cannot take the dot\nproduct because the second dimension of matrix a does not match\nthe first dimension of matrix b.'

## Exercise 4

In [7]:
# YOUR SOLUTION HERE
display(n.dot(a.transpose(), b))
display(n.dot(a, b.transpose()))
"""It is because when taking the dot product, order of dimension-
ality is taken into account. By this, I mean that a dot product 
of a 4x6 matrix and a 6x4 matrix yields a matrix that matches the
first dimension of the first matrix, followed by the second dimen-
sion of the second matrix (and vice versa for a dot product of a 
6x4 matrix and a 4x6 matrix)."""

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

array([[12., 12., 12., 12.,  8.,  8.],
       [12., 12., 12., 12.,  8.,  8.],
       [12., 12., 12., 12.,  8.,  8.],
       [12., 12., 12., 12.,  8.,  8.],
       [12., 12., 12., 12.,  8.,  8.],
       [12., 12., 12., 12.,  8.,  8.]])

'It is because when taking the dot product, order of dimension-\nality is taken into account. By this, I mean that a dot product \nof a 4x6 matrix and a 6x4 matrix yields a matrix that matches the\nfirst dimension of the first matrix, followed by the second dimen-\nsion of the second matrix (and vice versa for a dot product of a \n6x4 matrix and a 4x6 matrix).'

## Exercise 5

In [8]:
# YOUR SOLUTION HERE
def _printer():
    print("Hello, World!\n")

_printer()

Hello, World!



## Exercise 6

In [9]:
# YOUR SOLUTION HERE
def rand_sum_and_mean():
    c = n.random.rand(3, 3)
    d = n.random.rand(3, 3)
    _sum = n.sum(c) + n.sum(d)
    mean = _sum / (len(c) + len(d))
    print("Sum: {0}\nMean: {1}".format(_sum, mean))
    
rand_sum_and_mean()

Sum: 10.018153911747124
Mean: 1.6696923186245207


#Exercise 7

In [10]:
# YOUR SOLUTION HERE
def counter(arr):
     num = 0
     n.where(arr == 1, arr, 1)
     for i in arr:
         for j in i:
             if int(j) == 1:
                 num += 1
     return num

arr = [[0, 1, 3, 1], [3, 1, 1, 5]]
# n.where(1, 0, 1)
# y = n.where(2, 0, 1)
counter(arr)


4

## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [11]:
# YOUR SOLUTION HERE
import pandas as p
import numpy as n
a = p.DataFrame(n.ones((6,4))*2)
a

0    1    2    3
0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0
3  2.0  2.0  2.0  2.0
4  2.0  2.0  2.0  2.0
5  2.0  2.0  2.0  2.0

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [12]:
# YOUR SOLUTION HERE
b = n.ones((6, 4))
b = p.DataFrame(b)
b.iloc[range(4), range(4)] = 3
b

0    1    2    3
0  3.0  1.0  1.0  1.0
1  1.0  3.0  1.0  1.0
2  1.0  1.0  3.0  1.0
3  1.0  1.0  1.0  3.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [13]:
# YOUR SOLUTION HERE
a*b
"""We can multiply each value of matrix a to the value in the
corresponding coordinate of matrix b, but we cannot take the dot
product because the second dimension of matrix a does not match
the first dimension of matrix b."""

'We can multiply each value of matrix a to the value in the\ncorresponding coordinate of matrix b, but we cannot take the dot\nproduct because the second dimension of matrix a does not match\nthe first dimension of matrix b.'

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [21]:
# YOUR SOLUTION HERE
def counter(b):
     num = 0
     n.where(b == 1, b, 1)
     for i in b:
        if i == 1:
            num += 1
     return num

counter(b)

1

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [14]:
titanic_df = p.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [24]:
## YOUR SOLUTION HERE
titanic_df['name']

sex
female                      Allen, Miss. Elisabeth Walton
male                       Allison, Master. Hudson Trevor
female                       Allison, Miss. Helen Loraine
male                 Allison, Mr. Hudson Joshua Creighton
female    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                               ...                       
female                               Zabour, Miss. Hileni
female                              Zabour, Miss. Thamine
male                            Zakarian, Mr. Mapriededer
male                                  Zakarian, Mr. Ortin
male                                   Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [30]:
## YOUR SOLUTION HERE
is_female = titanic_df['sex'] = 'female'
female_df = titanic_df[is_female]
# There are 10 female passengers

KeyError: 'female'

## Exercise 14
How do you reset the index?

In [ ]:
## YOUR SOLUTION HERE

In [31]:
titanic_df.reset_index(drop=True)

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

          age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0     29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1      0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2      2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3     30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4     25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
...       ...    ...    ...     ...       ...      ...      ...  ...    ...   
1304  14.5000      1      0    2665   14.4542      NaN        C  NaN  328.0   
1305      NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   
1306  26.5000      0      0    2656    7.2250      NaN        C  NaN  304.0   
1307  27.0000      0      0    2670    7.2250      NaN        C  NaN    NaN   
1308  29.0000      0      0  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest     sex  
0                        St Louis, MO  female  
1     Montreal, PQ / Chesterville, ON  female  
2     Montreal, PQ / Chesterville, ON  female  
3     Montreal, PQ / Chesterville, ON  female  
4     Montreal, PQ / Chesterville, ON  female  
...                               ...     ...  
1304                              NaN  female  
1305                              NaN  female  
1306                              NaN  female  
1307                              NaN  female  
1308                              NaN  female  

[1309 rows x 14 columns]